linters:
  enable:
    - dupl
    - funlen
    - cyclop
    - gocognit

linters-settings:
  dupl:
    threshold: 150
  funlen:
    lines: 80
    statements: 50
  cyclop:
    max-complexity: 20
  gocognit:
    min-complexity: 20

issues:
  exclude-dirs:
    - cmd
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - dupl
