#!/bin/bash
set -e

# Note, despite my notes about not using LLM's, this is generated by Claude. I'd like to replace this with a more robust solution
# But for now, this will do I guess...

README="README.md"
PKGS="./pkg/api/... ./pkg/client/... ./pkg/scheduler/... ./pkg/controller/... ./pkg/kubelet/... ./pkg/store/..."

# Replace content between HTML comment markers in README
# Usage: replace_section "start-marker" "end-marker" "content"
replace_section() {
    local start="$1" end="$2" content="$3"
    awk -v start="$start" -v end="$end" -v content="$content" '
        $0 ~ start { print; printf "%s\n", content; skip=1; next }
        $0 ~ end   { skip=0 }
        !skip      { print }
    ' "$README" > "$README.tmp"
    mv "$README.tmp" "$README"
}

# --- Coverage ---

COV_RAW=$(go test -cover $PKGS 2>&1)
TOTAL_LINE=$(go test -coverprofile=coverage.out $PKGS > /dev/null 2>&1 && go tool cover -func=coverage.out | grep ^total)
TOTAL=$(echo "$TOTAL_LINE" | awk '{print $NF}')
echo "Coverage: $TOTAL"

COV_LINES="| Package | Coverage |
|---------|----------|"

for pkg in api client controller kubelet scheduler store; do
    pct=$(echo "$COV_RAW" | grep "miniku/pkg/$pkg" | awk '{for(i=1;i<=NF;i++) if($i ~ /^[0-9]+\.[0-9]+%/) print $i}')
    if [ -n "$pct" ]; then
        COV_LINES="$COV_LINES
| \`pkg/$pkg\` | $pct |"
    fi
done
COV_LINES="$COV_LINES
| **Total** | **$TOTAL** |"

replace_section "coverage-start" "coverage-end" "$COV_LINES"

# --- Benchmarks ---

echo "Running benchmarks..."
BENCH_RAW=$(go test -run='^$' -bench=. -benchmem ./... 2>&1)

BENCH_LINES="| Benchmark | ns/op | B/op | allocs/op |
|-----------|------:|-----:|----------:|"

# Pick representative sub-benchmarks: pods=100, nodes=10, size=100; skip Concurrent
while IFS= read -r line; do
    name=$(echo "$line" | awk '{print $1}' | sed 's/^Benchmark//;s/-[0-9]*$//')
    nsop=$(echo "$line" | awk '{print $3}')
    bop=$(echo "$line" | awk '{for(i=1;i<=NF;i++) if($(i+1)=="B/op") print $i}')
    aop=$(echo "$line" | awk '{for(i=1;i<=NF;i++) if($(i+1)=="allocs/op") print $i}')
    BENCH_LINES="$BENCH_LINES
| $name | $nsop | $bop | $aop |"
done < <(echo "$BENCH_RAW" | awk '/^Benchmark/ {
    name = $1
    if (name ~ /Concurrent/) next
    if (name ~ /\/pods=/ && name !~ /\/pods=100-/) next
    if (name ~ /\/nodes=/ && name !~ /\/nodes=10-/) next
    if (name ~ /\/size=/ && name !~ /\/size=100-/) next
    print
}')

replace_section "bench-start" "bench-end" "$BENCH_LINES"

echo "README updated."

if [ "$1" = "--html" ]; then
    go tool cover -html=coverage.out
fi
